# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='actual_fee_paid',
            new_name='fee_concession_percent',
        ),
        migrations.RemoveField(
            model_name='student',
            name='fee_concession',
        ),
        migrations.AddField(
            model_name='student',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.IntegerField(default=221),
            preserve_default=False,
        ),
    ]
