# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20170105_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reason_left',
            field=models.CharField(blank=True, choices=[('gone_to_regular_school', 'gone_to_regular_school'), ('started_work', 'started_work'), ('returned_to_village', 'returned_to_village'), ('returned_to_country', 'returned_to_country'), ('changed_location', 'changed_location'), ('stay_at_home', 'stay_at_home'), ('other', 'other')], max_length=30, null=True),
        ),
    ]
