# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170115_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='updated_last_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
