# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_remove_student_date_addded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fee_concession_percent',
        ),
        migrations.AddField(
            model_name='student',
            name='fathers_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_percent_rate_fixed',
            field=models.IntegerField(choices=[('0', 0), ('25', 15), ('50', 50), ('100', 100)], default=100),
        ),
        migrations.AddField(
            model_name='student',
            name='mothers_occupation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
