# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_studenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
