# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_studenthistory_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenthistory',
            name='pkss_class',
            field=models.CharField(max_length=255),
        ),
    ]
