# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 02:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_class_shift'),
        ('students', '0014_auto_20170218_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pkss_class_original',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pkss_class_original', to='classes.Class'),
            preserve_default=False,
        ),
    ]
