# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_auto_20170218_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_percent_rate_fixed',
            field=models.IntegerField(choices=[(0, 0), (25, 15), (50, 50), (100, 100)], default=100),
        ),
    ]
