# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_auto_20170219_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pkss_class_original',
            field=models.CharField(default='aa', max_length=255),
        ),
    ]
