# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-07 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_auto_20170329_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='fee_percent_rate_fixed',
            field=models.IntegerField(default=100),
        ),
    ]
