# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-08 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('principal', 'principal'), ('vice principal', 'vice principal'), ('teacher', 'teacher'), ('teacher aid', 'teacher aid')], max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=12)),
                ('date_joined', models.DateField()),
                ('starting_salary', models.IntegerField(blank=True, null=True)),
                ('current_salary', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('starting_qualifications', models.CharField(max_length=200)),
                ('current_qualifications', models.CharField(max_length=200)),
                ('starting_years_experience', models.IntegerField(blank=True, null=True)),
                ('currently_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True)),
                ('updated_last', models.DateField(auto_now=True)),
                ('updated_last_by', models.CharField(blank=True, max_length=255, null=True)),
                ('pkss_school', models.ManyToManyField(blank=True, to='schools.School')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
