# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_school_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('principal', 'principal'), ('vice principal', 'vice principal'), ('teacher', 'teacher'), ('teacher aid', 'teacher aid')], max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=12)),
                ('date_joined', models.DateField()),
                ('starting_salary', models.IntegerField(blank=True, null=True)),
                ('current_salary', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=12)),
                ('pkss_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
