# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-19 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schoolshift'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='pkss_school_shift',
            field=models.ManyToManyField(blank=True, to='schools.SchoolShift'),
        ),
    ]
