# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_shift'),
        ('teachers', '0002_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='level',
            field=models.CharField(choices=[('management', 'management'), ('principal', 'principal'), ('vice principal', 'vice principal'), ('teacher', 'teacher'), ('teacher aid', 'teacher aid')], max_length=255),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pkss_school',
        ),
        migrations.AddField(
            model_name='teacher',
            name='pkss_school',
            field=models.ManyToManyField(blank=True, to='schools.School'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
