# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20170105_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='current_qualifications',
            field=models.CharField(default='something', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(default='03002229999', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='starting_qualifications',
            field=models.CharField(default='something', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='starting_years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
