# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_currently_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='notes',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_last',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_last_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
