# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-08 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('datestamp', models.DateField(auto_now_add=True)),
                ('datestamp_change', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='absent', max_length=7)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('att_taker', models.CharField(blank=True, max_length=120, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day_of_month', models.DateField()),
                ('workdays_in_month', models.IntegerField()),
                ('non_weekend_workdays_off', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='NonScheduledHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday_date', models.DateField(default=datetime.date.today)),
                ('reason_for_holiday', models.TextField(max_length=700)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='nonscheduledholidays',
            unique_together=set([('school', 'holiday_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendancecalendar',
            unique_together=set([('school', 'first_day_of_month')]),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('student', 'attendance_date')]),
        ),
    ]
