# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20170105_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='datestamp_change',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'present'), ('absent', 'absent')], default='absent', max_length=7),
        ),
    ]
