# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_shift'),
        ('attendance', '0004_auto_20170105_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_day_of_month', models.DateField()),
                ('workdays_in_month', models.IntegerField()),
                ('non_weekend_workdays_off', models.IntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
        migrations.CreateModel(
            name='NonScheduledHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason_for_holiday', models.CharField(max_length=500)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
        ),
    ]
