# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20170118_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='att_taker',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
