# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-08 18:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('country', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('organization', models.CharField(blank=True, max_length=120, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('tier', models.CharField(blank=True, choices=[('plantinum', 'plantinum'), ('gold', 'gold'), ('silver', 'silver'), ('bronze', 'bronze')], max_length=24, null=True)),
                ('added', models.DateTimeField(auto_now=True)),
                ('regular_donor', models.BooleanField(default=False)),
                ('cycle', models.CharField(blank=True, choices=[('annual', 'annual'), ('semi_annual', 'semi_annual'), ('quarterly', 'quarterly')], max_length=12, null=True)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('next_expected_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField(default=datetime.date.today)),
                ('fiscal_year', models.CharField(choices=[('FY16', 'FY16'), ('FY17', 'FY17'), ('FY18', 'FY18')], default='FY17', max_length=24)),
                ('currency', models.CharField(choices=[('PKR', 'PKR'), ('USD', 'USD'), ('UKP', 'UKP'), ('Other', 'Other')], default='PKR', max_length=10)),
                ('amount_local_currency', models.IntegerField()),
                ('conversion_rate_if_not_PKR', models.IntegerField(verbose_name='Enter conversation rate to PKR, enter 1 for PKR')),
                ('amount_pkr', models.IntegerField(blank=True, null=True)),
                ('donation_notes', models.TextField(blank=True, max_length=2500, null=True)),
                ('contact_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.Donor')),
            ],
        ),
    ]
