# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='cycle',
            field=models.CharField(blank=True, choices=[('annual', 'annual'), ('semi_annual', 'semi_annual'), ('quarterly', 'quarterly')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='next_expected_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='regular_donor',
            field=models.BooleanField(default=False),
        ),
    ]
