# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_auto_20170205_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_log',
            name='conversion_rate_if_not_PKR',
            field=models.IntegerField(verbose_name='Enter conversation rate to PKR, enter 1 for PKR'),
        ),
    ]
