# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_auto_20170205_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='reg',
            field=models.IntegerField(default=900000),
            preserve_default=False,
        ),
    ]
