# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donor_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='donor',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
    ]
