# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-05-20 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schoolshift'),
        ('tattendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='school_shift',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolShift'),
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='time_came_in',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherattendance',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
