# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_auto_20170218_1733'),
        ('teachers', '0004_auto_20170105_2255'),
        ('tattendance', '0002_auto_20170219_1724'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherattendance',
            unique_together=set([('teacher', 'attendance_date', 'school')]),
        ),
    ]
