# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 16:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schoolshift'),
        ('tattendance', '0003_auto_20170228_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='school_shift',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.SchoolShift'),
        ),
    ]
