# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattendance', '0004_teacherattendance_school_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherattendance',
            name='time_came_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
