# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tattendance', '0005_teacherattendance_time_came_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherattendance',
            name='school',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
    ]
