# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=255)),
                ('class_section', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
