# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Play Group', 'Play Group'), ('Nursery', 'Nursery'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6')], max_length=255)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=255)),
                ('shift', models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], max_length=255)),
                ('school_class_section', models.CharField(blank=True, max_length=255, null=True)),
                ('currently_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, max_length=2500, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School')),
            ],
            options={
                'ordering': ['school_class_section'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set([('school', 'class_name', 'section')]),
        ),
    ]
