# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_shift'),
        ('classes', '0002_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
            preserve_default=False,
        ),
    ]
