# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('Nursery', 'Nursery'), ('M1', 'M1'), ('M2', 'M2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5')], max_length=255),
        ),
        migrations.AlterField(
            model_name='class',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=255),
        ),
    ]
