# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20161230_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(choices=[('Play Group', 'Play Group'), ('Nursery', 'Nursery'), ('M1', 'M1'), ('M2', 'M2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6')], max_length=255),
        ),
    ]
