# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_auto_20170105_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='shift',
            field=models.CharField(choices=[('morning', 'morning'), ('evening', 'evening')], default='morning', max_length=255),
            preserve_default=False,
        ),
    ]
