# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='access_level',
            field=models.CharField(choices=[('super', 'super'), ('manager', 'manager'), ('principal', 'principal'), ('staff', 'staff'), ('coordinator', 'coordinator'), ('accountant', 'accountant')], default='staff', max_length=255),
        ),
    ]
