# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='shift',
            field=models.CharField(default='morning', max_length=255),
            preserve_default=False,
        ),
    ]
